# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhiHuRX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiHuRX
pod 'Moya'
pod 'Moya/RxSwift'
pod 'Kingfisher'
pod 'HandyJSON'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'Then'
pod 'SwiftDate'
pod 'ZYBannerView'
pod 'MJRefresh'
end
